// Dataset for "Spot the Bot".
//
// Provenance & ethics: these are NOT scraped, identifiable Reddit users. They
// are anonymized/invented profiles. A handful are modeled on well-documented
// PUBLIC bot archetypes (karma-farming repost bots, crypto/giveaway spammers,
// aged "sleeper" astroturf accounts, AI-comment bots); the rest are authored to
// round out each difficulty tier with a balanced bot/human mix. Usernames are
// fictional. The `label` is the ground truth; `outcome` narrates the real-world
// success signal the game is about ("was the account eventually banned?").
//
// Each profile:
//   id, username, difficulty: 'easy'|'medium'|'hard', label: 'bot'|'human',
//   outcome (string), accountAgeDays, cakeDay, karma:{post,comment},
//   subreddits:[...], cadence (string), bio (string),
//   samplePosts:[{subreddit, age, score, text}],
//   tells:[...]  // shown on reveal — what gives it away (or why it's a human)

export const PROFILES = [
  // ----------------------------- EASY -----------------------------
  {
    id: 'e01',
    username: 'u/CryptoGiveaway_Elon',
    difficulty: 'easy',
    label: 'bot',
    outcome: 'Suspended site-wide 6 days after creation',
    accountAgeDays: 5,
    cakeDay: '2024-05-02',
    karma: { post: 340, comment: 2 },
    subreddits: ['r/CryptoMoonShots', 'r/dogecoin', 'r/SatoshiStreetBets'],
    cadence: '61 posts in 5 days, almost all between 02:00–04:30 UTC',
    bio: 'OFFICIAL giveaway 🚀 send 0.5 ETH get 1 ETH back!! link in profile',
    samplePosts: [
      { subreddit: 'r/dogecoin', age: '1d', score: 1, text: '🚀🚀 ELON official giveaway!! First 500 only, claim here 👉 [bit.ly link]' },
      { subreddit: 'r/CryptoMoonShots', age: '2d', score: 0, text: '🚀🚀 ELON official giveaway!! First 500 only, claim here 👉 [bit.ly link]' },
      { subreddit: 'r/SatoshiStreetBets', age: '2d', score: 1, text: '🚀🚀 ELON official giveaway!! First 500 only, claim here 👉 [bit.ly link]' },
    ],
    tells: [
      'Account is 5 days old with 340 post karma and only 2 comment karma — no real conversation.',
      'Identical copy-pasted giveaway text across three subreddits.',
      'Classic "send crypto, get double back" scam plus a shortened link.',
      'Inhuman posting cadence concentrated in a narrow nighttime window.',
    ],
  },
  {
    id: 'e02',
    username: 'u/maria_bakes_bread',
    difficulty: 'easy',
    label: 'human',
    outcome: 'Still active years later',
    accountAgeDays: 1490,
    cakeDay: '2020-04-18',
    karma: { post: 8200, comment: 14300 },
    subreddits: ['r/Breadit', 'r/AskBaking', 'r/castiron', 'r/gardening', 'r/CasualConversation'],
    cadence: 'A few posts/comments most days, spread across waking hours',
    bio: 'sourdough enthusiast, cast iron hoarder, killing one houseplant at a time',
    samplePosts: [
      { subreddit: 'r/Breadit', age: '2d', score: 540, text: 'First attempt at a 75% hydration loaf — crumb finally opened up! Recipe in comments if anyone wants it.' },
      { subreddit: 'r/AskBaking', age: '6d', score: 22, text: 'Honestly depends on your oven. Mine runs hot so I drop it 15°F and it fixed the over-browning.' },
      { subreddit: 'r/gardening', age: '11d', score: 88, text: 'Update on the tomatoes from last month — the epsom salt did nothing lol, it was just more sun.' },
    ],
    tells: [
      'Four-year-old account with a healthy mix of post AND comment karma.',
      'Posts in a coherent cluster of related hobby subs, with replies that answer specific questions.',
      'Natural, varied language; references its own past posts ("update on the tomatoes").',
      'Normal human cadence spread across the day.',
    ],
  },
  {
    id: 'e03',
    username: 'u/Linda_Watson8842',
    difficulty: 'easy',
    label: 'bot',
    outcome: 'Banned for spam 3 weeks after creation',
    accountAgeDays: 9,
    cakeDay: '2024-06-01',
    karma: { post: 12, comment: 470 },
    subreddits: ['r/AmItheAsshole', 'r/relationship_advice', 'r/tifu', 'r/AskReddit'],
    cadence: '200+ comments in 9 days, one every few minutes during bursts',
    bio: '',
    samplePosts: [
      { subreddit: 'r/AskReddit', age: '4h', score: 1, text: 'This is so true! Thanks for sharing 😊' },
      { subreddit: 'r/AmItheAsshole', age: '5h', score: 1, text: 'Wow, great point. Totally agree with this.' },
      { subreddit: 'r/tifu', age: '6h', score: 1, text: 'This made my day, thank you for posting!' },
    ],
    tells: [
      'Generic, vague affirmations ("so true!", "great point") that fit any thread.',
      'Username is a name + random 4 digits — a sign-up generator pattern.',
      'Comment-karma farming: 470 comment karma in 9 days, near-zero original posts.',
      'Bursty cadence of one short comment every few minutes.',
    ],
  },
  {
    id: 'e04',
    username: 'u/grumpy_devops_dad',
    difficulty: 'easy',
    label: 'human',
    outcome: 'Still active',
    accountAgeDays: 2600,
    cakeDay: '2018-01-12',
    karma: { post: 1100, comment: 53000 },
    subreddits: ['r/sysadmin', 'r/devops', 'r/kubernetes', 'r/daddit', 'r/homelab'],
    cadence: 'Bursts of comments on weekday lunch breaks, quiet on weekends',
    bio: 'on call so you don\'t have to. opinions are my own and also wrong',
    samplePosts: [
      { subreddit: 'r/kubernetes', age: '1d', score: 210, text: 'You almost never need a service mesh at your scale. Add it when the pain is real, not before. Been burned twice.' },
      { subreddit: 'r/daddit', age: '3d', score: 47, text: 'Two under two is a blur but it gets better around 3. Hang in there, sleep when you can.' },
      { subreddit: 'r/homelab', age: '8d', score: 33, text: 'That PSU is sketchy for a 24/7 box. Spend the extra $40, your data will thank you.' },
    ],
    tells: [
      'Long-lived account with enormous comment karma — a real participant, not a poster bot.',
      'Opinionated, experience-based replies with specifics and hedging ("been burned twice").',
      'Believable life texture: mixes professional subs with r/daddit.',
      'Human cadence tied to a work schedule (weekday lunches, quiet weekends).',
    ],
  },
  {
    id: 'e05',
    username: 'u/news_aggregator_v2',
    difficulty: 'easy',
    label: 'bot',
    outcome: 'Suspended after mass-report for spam',
    accountAgeDays: 21,
    cakeDay: '2024-05-20',
    karma: { post: 90, comment: 0 },
    subreddits: ['r/worldnews', 'r/politics', 'r/technology', 'r/Economics', 'r/science'],
    cadence: 'Exactly 12 link posts per day, evenly spaced every 2 hours',
    bio: '',
    samplePosts: [
      { subreddit: 'r/technology', age: '2h', score: 0, text: '[link] Breaking: New AI model announced — read more at example-news-site.net' },
      { subreddit: 'r/worldnews', age: '4h', score: 1, text: '[link] You won\'t believe what happened next — example-news-site.net' },
      { subreddit: 'r/Economics', age: '6h', score: 0, text: '[link] Markets react — full story example-news-site.net' },
    ],
    tells: [
      'Zero comment karma — never replies, only drops links.',
      'Mechanically perfect cadence: 12 posts/day every 2 hours.',
      'All links point to the same low-quality domain; clickbait phrasing.',
      'Three-week-old account spraying the same domain across many large subs.',
    ],
  },
  {
    id: 'e06',
    username: 'u/quiet_birdwatcher',
    difficulty: 'easy',
    label: 'human',
    outcome: 'Still active',
    accountAgeDays: 920,
    cakeDay: '2021-11-30',
    karma: { post: 4300, comment: 2100 },
    subreddits: ['r/birding', 'r/whatsthisbird', 'r/wildlifephotography', 'r/Maine'],
    cadence: 'Posts in clusters on weekends, mostly photos',
    bio: 'PNW transplant, ~210 species and counting 🦉',
    samplePosts: [
      { subreddit: 'r/whatsthisbird', age: '3d', score: 64, text: 'Northern flicker, red-shafted. The black mustache means male. Nice shot!' },
      { subreddit: 'r/birding', age: '9d', score: 410, text: 'Finally got a clear photo of the barred owl that\'s been taunting me all winter. Patience pays off.' },
      { subreddit: 'r/Maine', age: '20d', score: 30, text: 'Anyone know if the Scarborough Marsh boardwalk is open yet this season?' },
    ],
    tells: [
      'Niche, consistent topic expertise (correct bird ID with reasoning).',
      'Balanced post/comment karma over nearly three years.',
      'Local, specific questions ("Scarborough Marsh boardwalk") — lived experience.',
      'Weekend photo cadence matches a real hobby.',
    ],
  },
  {
    id: 'e07',
    username: 'u/FreeRobux_Generator',
    difficulty: 'easy',
    label: 'bot',
    outcome: 'Banned within 48 hours',
    accountAgeDays: 2,
    cakeDay: '2024-06-10',
    karma: { post: 5, comment: 0 },
    subreddits: ['r/RobloxFreeStuff', 'r/gaming', 'r/teenagers'],
    cadence: '30 posts in 2 days, all identical',
    bio: 'FREE ROBUX no human verification (real 2024) link in bio',
    samplePosts: [
      { subreddit: 'r/teenagers', age: '3h', score: 0, text: 'FREE ROBUX GENERATOR 2024 ✅ no verification, working ✅ → freerobux-now.xyz' },
      { subreddit: 'r/gaming', age: '5h', score: 0, text: 'FREE ROBUX GENERATOR 2024 ✅ no verification, working ✅ → freerobux-now.xyz' },
    ],
    tells: [
      'Two-day-old account doing nothing but posting a "free currency" scam.',
      'Suspicious off-platform domain and "no verification" bait.',
      'Identical text every time, zero engagement, zero comment karma.',
    ],
  },
  {
    id: 'e08',
    username: 'u/throwaway_for_advice',
    difficulty: 'easy',
    label: 'human',
    outcome: 'Still active (intentional throwaway)',
    accountAgeDays: 40,
    cakeDay: '2024-05-01',
    karma: { post: 95, comment: 60 },
    subreddits: ['r/legaladvice', 'r/personalfinance'],
    cadence: 'Sporadic; a flurry around one situation, then silence',
    bio: '',
    samplePosts: [
      { subreddit: 'r/legaladvice', age: '12d', score: 140, text: 'My landlord kept the deposit and won\'t respond. This is in Ohio. I have texts and photos from move-out. What are my options?' },
      { subreddit: 'r/legaladvice', age: '11d', score: 8, text: 'Thanks — I didn\'t know small claims was that cheap. I\'ll send the demand letter first like you said.' },
      { subreddit: 'r/personalfinance', age: '30d', score: 22, text: 'Update: got the deposit back after the demand letter. Thank you all, this sub is a lifesaver.' },
    ],
    tells: [
      'New, low-karma account — but it is a deliberate throwaway, a normal human pattern.',
      'A single coherent real-life situation with follow-up replies and a resolution.',
      'Specific, consistent details (Ohio, deposit, demand letter) across posts.',
      'Engages with answers rather than ignoring the thread.',
    ],
  },

  // ----------------------------- MEDIUM -----------------------------
  {
    id: 'm01',
    username: 'u/DailyFactsAndMore',
    difficulty: 'medium',
    label: 'bot',
    outcome: 'Suspended after 5 months for vote manipulation',
    accountAgeDays: 150,
    cakeDay: '2024-01-08',
    karma: { post: 41000, comment: 120 },
    subreddits: ['r/interestingasfuck', 'r/Damnthatsinteresting', 'r/nextfuckinglevel', 'r/oddlysatisfying'],
    cadence: 'Posts the most-upvoted item from a year ago, daily',
    bio: 'sharing cool stuff 👍',
    samplePosts: [
      { subreddit: 'r/Damnthatsinteresting', age: '1d', score: 22000, text: '[reposted image] This 2,000 year old Roman road is still in use today' },
      { subreddit: 'r/interestingasfuck', age: '4d', score: 18000, text: '[reposted video] How they move a house in one piece' },
      { subreddit: 'r/oddlysatisfying', age: '7d', score: 9000, text: '[reposted gif] Perfectly fitting the last puzzle piece' },
    ],
    tells: [
      'Huge post karma but almost no comments — a karma-farming repost bot.',
      'Content is exactly the top post from the same sub ~1 year earlier (reposts).',
      'Generic title style, no original commentary, never replies to its own threads.',
      'Such accounts are often aged, then sold; this one was caught manipulating votes.',
    ],
  },
  {
    id: 'm02',
    username: 'u/hannah_grad_school',
    difficulty: 'medium',
    label: 'human',
    outcome: 'Still active',
    accountAgeDays: 380,
    cakeDay: '2023-06-15',
    karma: { post: 60, comment: 3400 },
    subreddits: ['r/GradSchool', 'r/AskAcademia', 'r/labrats', 'r/Anxiety', 'r/coffee'],
    cadence: 'Comment-heavy in evenings, dries up during exam weeks',
    bio: '',
    samplePosts: [
      { subreddit: 'r/labrats', age: '2d', score: 75, text: 'Your western is probably over-transferred. Drop the transfer time and check your ladder didn\'t run off. Been there at 2am.' },
      { subreddit: 'r/Anxiety', age: '5d', score: 30, text: 'Therapy + actually using the breathing stuff helped me more than I expected. It feels dumb until it works.' },
      { subreddit: 'r/coffee', age: '9d', score: 12, text: 'Aeropress inverted, 15g/250g, 2 min. Forgiving and cheap, perfect for a grad student budget.' },
    ],
    tells: [
      'Comment-dominant karma — a conversationalist, not a poster bot.',
      'Domain-specific, lived-in detail (western blots, "been there at 2am").',
      'Emotional nuance in r/Anxiety that bots rarely produce.',
      'Activity dips during plausible real-life events (exam weeks).',
    ],
  },
  {
    id: 'm03',
    username: 'u/marketwatch_insights',
    difficulty: 'medium',
    label: 'bot',
    outcome: 'Banned for undisclosed promotion',
    accountAgeDays: 210,
    cakeDay: '2023-12-01',
    karma: { post: 800, comment: 2600 },
    subreddits: ['r/stocks', 'r/investing', 'r/wallstreetbets', 'r/StockMarket'],
    cadence: 'Steady, but every 8–10 comments slips in the same app name',
    bio: 'markets | data | not financial advice',
    samplePosts: [
      { subreddit: 'r/investing', age: '1d', score: 4, text: 'Good breakdown. I track all this in TradeLensPro now, the alerts caught this move early tbh.' },
      { subreddit: 'r/stocks', age: '2d', score: 9, text: 'Solid DD. Been using TradeLensPro for the screener, way better than the free tools imo.' },
      { subreddit: 'r/StockMarket', age: '3d', score: 2, text: 'Agreed. TradeLensPro flagged this last week, worth a look if you want the edge.' },
    ],
    tells: [
      'Looks like a normal commenter, but repeatedly plugs the same product name.',
      'Plugs are spaced out to seem organic — classic astroturf cadence.',
      'Slightly templated praise ("solid DD", "good breakdown") wrapping the ad.',
      'Undisclosed promotion across multiple finance subs got it banned.',
    ],
  },
  {
    id: 'm04',
    username: 'u/PNW_trailrunner',
    difficulty: 'medium',
    label: 'human',
    outcome: 'Still active',
    accountAgeDays: 1700,
    cakeDay: '2019-10-22',
    karma: { post: 2200, comment: 9100 },
    subreddits: ['r/trailrunning', 'r/running', 'r/Ultralight', 'r/Seattle', 'r/AdvancedRunning'],
    cadence: 'Long thoughtful comments on weekends, race reports seasonally',
    bio: 'slow but stubborn. 3 hundos, 0 podiums',
    samplePosts: [
      { subreddit: 'r/AdvancedRunning', age: '4d', score: 88, text: 'Race report: Cascade Crest 100. Blew up at mile 70 chasing a stretch goal, walked it in. Lessons: respect the heat, eat earlier.' },
      { subreddit: 'r/Ultralight', age: '10d', score: 41, text: 'For a wet PNW shoulder season I\'d take the slightly heavier shelter. Condensation will ruin your night otherwise.' },
      { subreddit: 'r/Seattle', age: '15d', score: 19, text: 'Tiger Mountain is a zoo on Saturdays now. Go at dawn or hit Cougar instead.' },
    ],
    tells: [
      'Years of consistent, niche expertise (ultra running, local trails).',
      'A genuine long-form race report with self-critical specifics.',
      'Local knowledge that can\'t be templated ("Tiger Mountain… go at dawn").',
      'Comment-heavy, seasonal cadence matching a real hobbyist.',
    ],
  },
  {
    id: 'm05',
    username: 'u/Helpful_Answer_Bot42',
    difficulty: 'medium',
    label: 'bot',
    outcome: 'Suspended after users flagged AI-generated replies',
    accountAgeDays: 95,
    cakeDay: '2024-03-05',
    karma: { post: 30, comment: 5200 },
    subreddits: ['r/explainlikeimfive', 'r/answers', 'r/NoStupidQuestions', 'r/AskReddit'],
    cadence: 'Replies within seconds of new questions, around the clock, no gaps',
    bio: '',
    samplePosts: [
      { subreddit: 'r/NoStupidQuestions', age: '1h', score: 3, text: 'Great question! There are several factors to consider. First, it is important to understand that... In conclusion, it depends on the situation.' },
      { subreddit: 'r/explainlikeimfive', age: '2h', score: 1, text: 'That\'s a great question! To put it simply, there are a few key points. Firstly... Ultimately, it varies case by case.' },
      { subreddit: 'r/answers', age: '3h', score: 2, text: 'Excellent question! Let\'s break it down. On one hand... on the other hand... I hope this helps!' },
    ],
    tells: [
      'Formulaic AI scaffolding: "Great question!", "Firstly… In conclusion…", "I hope this helps!"',
      'Answers are confidently empty — lots of structure, no specifics.',
      'Replies within seconds, 24/7, with no human downtime.',
      'Comment count is enormous for a 3-month-old account.',
    ],
  },
  {
    id: 'm06',
    username: 'u/dad_jokes_and_diy',
    difficulty: 'medium',
    label: 'human',
    outcome: 'Still active',
    accountAgeDays: 2100,
    cakeDay: '2019-04-30',
    karma: { post: 15000, comment: 22000 },
    subreddits: ['r/DIY', 'r/woodworking', 'r/Dadjokes', 'r/fixit', 'r/HomeImprovement'],
    cadence: 'Evenings and weekends; posts build albums, comments help others',
    bio: 'measure twice, post once',
    samplePosts: [
      { subreddit: 'r/woodworking', age: '3d', score: 1200, text: 'Built my daughter a loft bed from the plans you all helped me tweak. Album inside, mistakes and all.' },
      { subreddit: 'r/fixit', age: '7d', score: 60, text: 'That\'s a failing capacitor, you can usually see the bulge on top. $3 part, 20 min job if you can solder.' },
      { subreddit: 'r/Dadjokes', age: '12d', score: 4300, text: 'I told my kids I\'d name a continent after them. They were like "no way." I said "Africa? more like A-yes-a."' },
    ],
    tells: [
      'High karma in BOTH posts and comments over many years.',
      'Posts show original work ("mistakes and all") and reference community help.',
      'Practical, specific repair advice with real numbers.',
      'Coherent persona (handy dad) consistent across subs.',
    ],
  },
  {
    id: 'm07',
    username: 'u/Sophia_Loves_Travel',
    difficulty: 'medium',
    label: 'bot',
    outcome: 'Banned for romance-scam patterns',
    accountAgeDays: 120,
    cakeDay: '2024-02-15',
    karma: { post: 600, comment: 410 },
    subreddits: ['r/solotravel', 'r/relationships', 'r/dating_advice', 'r/widowers'],
    cadence: 'Warm, friendly comments steering toward DMs',
    bio: 'nurse 🩺 | love to travel ✈️ | God is good',
    samplePosts: [
      { subreddit: 'r/widowers', age: '2d', score: 5, text: 'I lost my husband too, I understand your pain so deeply. You seem like such a kind soul. Feel free to message me anytime ❤️' },
      { subreddit: 'r/dating_advice', age: '5d', score: 3, text: 'Honestly the best connections start with a simple chat. I\'m always happy to talk, just DM me 😊' },
      { subreddit: 'r/solotravel', age: '8d', score: 7, text: 'Travel taught me to trust good people. If you ever want a travel buddy or just to chat, my DMs are open!' },
    ],
    tells: [
      'Over-warm, emotionally targeted replies that quickly push to private DMs.',
      'Curated "trustworthy" persona (nurse, faith, travel) common in romance scams.',
      'Targets vulnerable communities (r/widowers).',
      'Repeated "DM me / message me anytime" steering off public threads.',
    ],
  },
  {
    id: 'm08',
    username: 'u/just_here_lurking_99',
    difficulty: 'medium',
    label: 'human',
    outcome: 'Still active',
    accountAgeDays: 1300,
    cakeDay: '2021-07-07',
    karma: { post: 5, comment: 740 },
    subreddits: ['r/movies', 'r/television', 'r/PS5', 'r/buildapc'],
    cadence: 'Occasional comments, often weeks apart',
    bio: '',
    samplePosts: [
      { subreddit: 'r/buildapc', age: '6d', score: 28, text: 'Don\'t cheap out on the PSU, that\'s the one part that can take everything else with it. Learned the hard way.' },
      { subreddit: 'r/movies', age: '24d', score: 15, text: 'The runtime didn\'t bother me, the pacing did. Could\'ve cut the whole second subplot.' },
      { subreddit: 'r/PS5', age: '40d', score: 6, text: 'Still rocking mine, no complaints. The controller battery is the only annoyance.' },
    ],
    tells: [
      'Low karma and infrequent posting — but that is normal "lurker" behavior, not a bot.',
      'Opinions are specific and a little contrarian (pacing vs. runtime).',
      'Long, irregular gaps between comments — bots tend to be relentless.',
      'Consistent low-key consumer-tech/movies interests over years.',
    ],
  },

  // ----------------------------- HARD -----------------------------
  {
    id: 'h01',
    username: 'u/concerned_local_voter',
    difficulty: 'hard',
    label: 'bot',
    outcome: 'Suspended in a coordinated-influence takedown',
    accountAgeDays: 800,
    cakeDay: '2022-04-15',
    karma: { post: 1900, comment: 6400 },
    subreddits: ['r/politics', 'r/news', 'r/aww', 'r/food', 'r/local_city_sub'],
    cadence: 'Normal-looking, but political activity spikes around election dates',
    bio: 'just a regular person who pays attention',
    samplePosts: [
      { subreddit: 'r/aww', age: '2d', score: 60, text: 'What a good boy! 🐶' },
      { subreddit: 'r/local_city_sub', age: '6d', score: 120, text: 'We can\'t trust the current council on the budget. Remember this in November. Share with everyone you know.' },
      { subreddit: 'r/politics', age: '6d', score: 40, text: 'Both sides are corrupt but THIS one is the real threat. Wake up before it\'s too late.' },
    ],
    tells: [
      'Aged "sleeper" account with normal-looking filler (r/aww, r/food) for cover.',
      'Political activity clusters suspiciously around election dates.',
      'Repetitive call-to-action framing ("share with everyone", "wake up").',
      'Caught in a coordinated influence-operation takedown — hard to spot solo.',
    ],
  },
  {
    id: 'h02',
    username: 'u/em_reads_too_much',
    difficulty: 'hard',
    label: 'human',
    outcome: 'Still active',
    accountAgeDays: 240,
    cakeDay: '2024-02-28',
    karma: { post: 9, comment: 980 },
    subreddits: ['r/books', 'r/Fantasy', 'r/suggestmeabook', 'r/52book'],
    cadence: 'Daily-ish comments in book subs, occasional binge threads',
    bio: 'currently reading too many things at once',
    samplePosts: [
      { subreddit: 'r/Fantasy', age: '1d', score: 35, text: 'I bounced off it at first too but the POV switch in part two completely changed the book for me. Stick with it to ch. 14.' },
      { subreddit: 'r/suggestmeabook', age: '3d', score: 18, text: 'If you liked that, try Piranesi — same lonely-architecture vibe but stranger. Short, too.' },
      { subreddit: 'r/52book', age: '5d', score: 9, text: 'Book 19/52. DNF\'d two this month and I\'m weirdly proud of letting myself quit bad books.' },
    ],
    tells: [
      'Young account with low post karma — superficially "new and suspicious".',
      'But replies show genuine reading memory ("the POV switch… ch. 14").',
      'Specific, idiosyncratic taste and self-reflection (proud of DNF-ing).',
      'A real newer user, not a bot — recency alone is not guilt.',
    ],
  },
  {
    id: 'h03',
    username: 'u/PracticalReviewGuy',
    difficulty: 'hard',
    label: 'bot',
    outcome: 'Banned for affiliate spam after months of cover activity',
    accountAgeDays: 540,
    cakeDay: '2023-01-10',
    karma: { post: 3100, comment: 7800 },
    subreddits: ['r/BuyItForLife', 'r/gadgets', 'r/CrappyDesign', 'r/mildlyinteresting', 'r/reviews'],
    cadence: 'Lots of harmless comments; product recs spike on weekends',
    bio: 'I test stuff so you don\'t have to',
    samplePosts: [
      { subreddit: 'r/mildlyinteresting', age: '2d', score: 200, text: 'The way the tiles almost line up but don\'t. lol' },
      { subreddit: 'r/BuyItForLife', age: '4d', score: 30, text: 'After testing 6 of these, the AceGrip Pro was clearly the most durable. Full breakdown on my site (link in profile).' },
      { subreddit: 'r/gadgets', age: '5d', score: 22, text: 'Honestly the AceGrip Pro punches above its price. Couldn\'t find a better one in 3 weeks of testing.' },
    ],
    tells: [
      'Builds credibility with months of innocuous comments before monetizing.',
      'Funnels to "my site (link in profile)" with affiliate-style product pushing.',
      'Same product name recurs across reviews despite "objective testing" framing.',
      'The cover activity makes it look human until you notice the funnel.',
    ],
  },
  {
    id: 'h04',
    username: 'u/retired_nurse_pat',
    difficulty: 'hard',
    label: 'human',
    outcome: 'Still active',
    accountAgeDays: 3000,
    cakeDay: '2018-02-01',
    karma: { post: 400, comment: 18000 },
    subreddits: ['r/AskDocs', 'r/nursing', 'r/knitting', 'r/Genealogy', 'r/politics'],
    cadence: 'Daytime comments, very chatty, strong opinions in r/politics',
    bio: 'RN x 30 yrs, retired. ask me about compression socks',
    samplePosts: [
      { subreddit: 'r/nursing', age: '1d', score: 240, text: 'New grads: chart as you go. The shift you "remember it later" is the shift you forget the one thing that matters.' },
      { subreddit: 'r/politics', age: '3d', score: 90, text: 'I\'ve voted in every election since 1980 and I\'ve never seen it this bad. We have to actually show up.' },
      { subreddit: 'r/knitting', age: '6d', score: 55, text: 'Frogged the whole yoke twice. At my age I\'ve made peace with the rip-it-back ritual lol.' },
    ],
    tells: [
      'Heavy political posting could look "agenda-driven" — but it is one slice of a rich profile.',
      '30-year coherent persona (nursing wisdom, knitting, genealogy) across a decade.',
      'Idiosyncratic human details ("frogged the yoke twice", "since 1980").',
      'Strong opinions ≠ bot; this is a real, opinionated long-term user.',
    ],
  },
  {
    id: 'h05',
    username: 'u/TechBro_Takes',
    difficulty: 'hard',
    label: 'bot',
    outcome: 'Suspended as part of an AI persona-network',
    accountAgeDays: 300,
    cakeDay: '2023-11-20',
    karma: { post: 700, comment: 4100 },
    subreddits: ['r/technology', 'r/Futurology', 'r/startups', 'r/artificial'],
    cadence: 'Coherent, opinionated, on-topic — but never makes a factual error or typo',
    bio: 'building the future, one take at a time',
    samplePosts: [
      { subreddit: 'r/Futurology', age: '1d', score: 60, text: 'The real bottleneck isn\'t compute, it\'s energy and regulation. Counterintuitive, but the next decade is decided in policy rooms, not labs.' },
      { subreddit: 'r/startups', age: '2d', score: 45, text: 'Counterpoint: premature scaling kills more startups than competition does. Most teams optimize the wrong metric early.' },
      { subreddit: 'r/artificial', age: '4d', score: 80, text: 'It is a great question. The interesting tension is between capability and alignment, and most coverage conflates the two.' },
    ],
    tells: [
      'Unusually polished, balanced "thought-leader" takes with zero typos or slang slips.',
      'Always hedged and quotable — reads like generated commentary, never personal.',
      'No real life leaks through: no anecdotes, no off-topic subs, no mistakes.',
      'Was one node in a network of near-identical AI persona accounts.',
    ],
  },
  {
    id: 'h06',
    username: 'u/sam_new_to_reddit',
    difficulty: 'hard',
    label: 'human',
    outcome: 'Still active',
    accountAgeDays: 30,
    cakeDay: '2024-05-15',
    karma: { post: 210, comment: 40 },
    subreddits: ['r/houseplants', 'r/plantclinic', 'r/IndoorGarden'],
    cadence: 'Bursty — joined, posted a lot the first week, then settled down',
    bio: 'just got way too into plants during a move',
    samplePosts: [
      { subreddit: 'r/plantclinic', age: '2d', score: 18, text: 'Update: the monstera you all said to repot is pushing a new leaf! Thank you, I was about to give up on it.' },
      { subreddit: 'r/houseplants', age: '20d', score: 180, text: 'My first ever shelf is full and I have a problem. Send help (and more plants).' },
      { subreddit: 'r/plantclinic', age: '28d', score: 12, text: 'Is this overwatering or underwatering? Leaves yellow but soil still damp. New plant parent, sorry if obvious!' },
    ],
    tells: [
      'New account + high post-to-comment ratio can pattern-match to "poster bot".',
      'But content is a believable enthusiastic-beginner arc with follow-ups.',
      'Asks naive questions and thanks people — engages like a real newcomer.',
      'Narrow genuine interest born from a life event ("during a move").',
    ],
  },
  {
    id: 'h07',
    username: 'u/EverydayThoughts_22',
    difficulty: 'hard',
    label: 'bot',
    outcome: 'Banned after karma threshold reached and account repurposed',
    accountAgeDays: 430,
    cakeDay: '2023-04-25',
    karma: { post: 2400, comment: 3300 },
    subreddits: ['r/showerthoughts', 'r/Jokes', 'r/AskReddit', 'r/LifeProTips'],
    cadence: 'Reposts top-of-all-time content from each sub on a slow rotation',
    bio: '',
    samplePosts: [
      { subreddit: 'r/Showerthoughts', age: '3d', score: 8000, text: 'Your stomach thinks all potatoes are mashed.' },
      { subreddit: 'r/LifeProTips', age: '9d', score: 5400, text: 'LPT: If you struggle to wake up, put your alarm across the room.' },
      { subreddit: 'r/Jokes', age: '16d', score: 6100, text: 'Why don\'t scientists trust atoms? Because they make up everything.' },
    ],
    tells: [
      'Every post is a verbatim all-time-top repost from that exact sub.',
      'Slow rotation and mixed post/comment karma mimic an organic account.',
      'Never engages in comments on its own posts — pure recycled content.',
      'Goal is to farm karma to a threshold, then sell/repurpose the account.',
    ],
  },
  {
    id: 'h08',
    username: 'u/mike_argues_online',
    difficulty: 'hard',
    label: 'human',
    outcome: 'Still active (and still arguing)',
    accountAgeDays: 2400,
    cakeDay: '2018-11-11',
    karma: { post: 80, comment: -1200 },
    subreddits: ['r/changemyview', 'r/politics', 'r/sports', 'r/PoliticalDiscussion'],
    cadence: 'Long combative comments at all hours, frequently downvoted',
    bio: 'wrong on the internet since dial-up',
    samplePosts: [
      { subreddit: 'r/changemyview', age: '1d', score: -30, text: 'Δ I\'ll grant the second point, that\'s a fair distinction I hadn\'t weighed. Still disagree on the first for the reasons above.' },
      { subreddit: 'r/sports', age: '4d', score: -8, text: 'Hot take but the dynasty was overrated — they never beat a healthy rival. Come at me.' },
      { subreddit: 'r/PoliticalDiscussion', age: '7d', score: 14, text: 'Source? Because the actual bill text says the opposite of what you\'re claiming. Page 41.' },
    ],
    tells: [
      'Negative comment karma looks "toxic/throwaway" — but it is a real argumentative human.',
      'Awards a CMV delta and concedes a point — bots rarely change their mind.',
      'Cites specifics ("page 41", "never beat a healthy rival") in genuine debate.',
      'Decade-long consistent contrarian persona; unpopular ≠ inauthentic.',
    ],
  },
];

// Group profiles by difficulty for quick round selection.
export const BY_DIFFICULTY = PROFILES.reduce((acc, p) => {
  (acc[p.difficulty] ||= []).push(p);
  return acc;
}, {});

export const DIFFICULTIES = [
  { id: 'easy', label: 'Easy', blurb: 'Obvious spam bots vs. clearly real people.' },
  { id: 'medium', label: 'Medium', blurb: 'Karma farmers, AI repliers, and subtle promoters.' },
  { id: 'hard', label: 'Hard', blurb: 'Sleeper astroturf and humans who look suspicious.' },
];
