// Room data for Eggerland. Keys are 'col,row' positions in the 10×10
// overworld grid (row 0 = north). Rooms keyed 'test-*' are DEV-only
// playgrounds reachable via ?room=test-... and are not part of the map.
//
// HAND-TRANSCRIBED STARTER SET — this file will be regenerated by
// tools/extract.mjs from the original game map once the map PNG is
// available (see tools/README.md). Terrain chars are defined in tiles.js.
// `exits` gives the tile offset of the door on each edge, or null.

export { ROOM_W, ROOM_H } from './tiles.js';

export const ROOMS = {
  // Stage 1 — meet the blocks.
  '0,9': {
    stage: 1,
    terrain: [
      '..............',
      '..T........T..',
      '..............',
      '....TT........',
      '..............',
      '..............',
      '......T.......',
      '..............',
      '..T........T..',
      '..............',
    ],
    entities: [
      { t: 'player', x: 1, y: 8 },
      { t: 'heart', x: 4, y: 2 },
      { t: 'heart', x: 10, y: 6 },
      { t: 'emerald', x: 7, y: 4 },
      { t: 'chest', x: 12, y: 1 },
      { t: 'snakey', x: 6, y: 5 },
    ],
    exits: { n: 7, e: 5, s: null, w: null },
  },

  // Stage 2 — cross the stream on an emerald raft.
  '1,9': {
    stage: 2,
    terrain: [
      '......~.......',
      '..T...~....T..',
      '......~.......',
      '......~..TT...',
      '......~.......',
      '......~.......',
      '..TT..~.......',
      '......~.......',
      '......~.......',
      '......~.......',
    ],
    entities: [
      { t: 'player', x: 1, y: 7 },
      { t: 'emerald', x: 4, y: 4 },
      { t: 'heart', x: 2, y: 2 },
      { t: 'heart', x: 11, y: 2 },
      { t: 'heart', x: 10, y: 7 },
      { t: 'leeper', x: 10, y: 4 },
      { t: 'chest', x: 12, y: 8 },
    ],
    exits: { n: 7, e: 5, w: 5, s: null },
  },

  // Stage 3 — hide from the Medusa behind emerald blocks.
  '2,9': {
    stage: 3,
    terrain: [
      '..............',
      '.#..........#.',
      '...#..........',
      '..............',
      '........#.....',
      '..............',
      '..............',
      '..............',
      '..............',
      '..............',
    ],
    entities: [
      { t: 'player', x: 10, y: 7 },
      { t: 'medusa', x: 3, y: 4 },
      { t: 'emerald', x: 2, y: 2 },
      { t: 'emerald', x: 5, y: 6 },
      { t: 'heart', x: 1, y: 4 },
      { t: 'heart', x: 3, y: 8 },
      { t: 'heart', x: 10, y: 2 },
      { t: 'chest', x: 12, y: 8 },
    ],
    exits: { w: 5, n: 7, e: null, s: null },
  },

  // Stage 4 — slow sand and sleepy Leepers.
  '0,8': {
    stage: 4,
    terrain: [
      '..............',
      '..ssss....T...',
      '..ssss........',
      '..ssss........',
      '......TT......',
      '..............',
      '....T.....ss..',
      '..........ss..',
      '..............',
      '..............',
    ],
    entities: [
      { t: 'player', x: 7, y: 8 },
      { t: 'leeper', x: 7, y: 3 },
      { t: 'leeper', x: 5, y: 6 },
      { t: 'heart', x: 3, y: 2 },
      { t: 'heart', x: 11, y: 6 },
      { t: 'heart', x: 12, y: 1 },
      { t: 'chest', x: 1, y: 8 },
    ],
    exits: { s: 7, e: 5, n: null, w: null },
  },

  // Stage 5 — one-way arrows, and Rocky wants a word.
  '1,8': {
    stage: 5,
    terrain: [
      '..............',
      '..TTTTTTTTT...',
      '..............',
      '...>>>........',
      '..T...T.......',
      '..............',
      '..T...T.......',
      '...<<<........',
      '..............',
      '..............',
    ],
    entities: [
      { t: 'player', x: 7, y: 8 },
      { t: 'rocky', x: 9, y: 5 },
      { t: 'heart', x: 4, y: 5 },
      { t: 'heart', x: 12, y: 2 },
      { t: 'heart', x: 1, y: 5 },
      { t: 'chest', x: 12, y: 8 },
    ],
    exits: { s: 7, w: 5, e: 5, n: null },
  },

  // Stage 6 — the Gol wakes when the last heart is taken.
  '2,8': {
    stage: 6,
    terrain: [
      '..............',
      '......#.......',
      '..............',
      '..TT.....TT...',
      '..............',
      '..............',
      '....#..#......',
      '..............',
      '..............',
      '..............',
    ],
    entities: [
      { t: 'player', x: 7, y: 8 },
      { t: 'gol', x: 7, y: 2 },
      { t: 'skull', x: 12, y: 1 },
      { t: 'snakey', x: 5, y: 5 },
      { t: 'emerald', x: 9, y: 4 },
      { t: 'heart', x: 2, y: 2 },
      { t: 'heart', x: 7, y: 7 },
      { t: 'heart', x: 12, y: 5 },
      { t: 'chest', x: 1, y: 1 },
    ],
    exits: { s: 7, w: 5, n: null, e: null },
  },

  // --- DEV test rooms (?room=test-...) --------------------------------

  'test-shots': {
    stage: 0,
    terrain: [
      '..............',
      '..............',
      '....~~~~......',
      '..............',
      '..............',
      '..............',
      '..............',
      '..............',
      '..............',
      '..............',
    ],
    entities: [
      { t: 'player', x: 1, y: 8 },
      { t: 'heart', x: 2, y: 1 },
      { t: 'heart', x: 10, y: 1 },
      { t: 'chest', x: 12, y: 8 },
      { t: 'snakey', x: 4, y: 5 },
      { t: 'rocky', x: 9, y: 6 },
      { t: 'alma', x: 12, y: 3 },
      { t: 'emerald', x: 6, y: 5 },
    ],
    exits: { n: null, s: null, e: null, w: null },
  },

  'test-donmedusa': {
    stage: 0,
    terrain: [
      '..............',
      '..............',
      '..............',
      '..............',
      '....####......',
      '..............',
      '..............',
      '..............',
      '..............',
      '..............',
    ],
    entities: [
      { t: 'player', x: 1, y: 8 },
      { t: 'don-medusa', x: 2, y: 2 },
      { t: 'leeper', x: 10, y: 6 },
      { t: 'heart', x: 12, y: 2 },
      { t: 'heart', x: 6, y: 6 },
      { t: 'chest', x: 12, y: 8 },
    ],
    exits: { n: null, s: null, e: null, w: null },
  },

  'test-gol-skull': {
    stage: 0,
    terrain: [
      '..............',
      '......#.......',
      '..............',
      '..............',
      '..............',
      '..............',
      '..............',
      '..............',
      '..............',
      '..............',
    ],
    entities: [
      { t: 'player', x: 7, y: 8 },
      { t: 'gol', x: 7, y: 2 },
      { t: 'skull', x: 1, y: 1 },
      { t: 'emerald', x: 2, y: 3 },
      { t: 'heart', x: 3, y: 3 },
      { t: 'heart', x: 10, y: 5 },
      { t: 'chest', x: 12, y: 1 },
    ],
    exits: { n: null, s: null, e: null, w: null },
  },
};
