"""Emit forward-pass fixtures from the weights that actually ship.

Deliberately reads games/pet-zoo/ink/weights.js rather than an in-memory model. The point
of these fixtures is to hold ink/model.js to the same answer as numpy, so they have to be
computed from the same quantised weights the browser will load — fixtures taken from the
full-precision model before quantising would leave a gap that looks exactly like a bug.

    python3 export_fixtures.py --digits path/to/digits \
        --weights ../../games/pet-zoo/ink/weights.js \
        --out ../../games/pet-zoo/tests/ink-fixtures.js
"""

import argparse
import base64
import json
import pathlib
import re

import numpy as np

from train import CLASSES, Net, load_digits, split


def read_weights(path):
    text = pathlib.Path(path).read_text()
    layers = json.loads(re.search(r"export const LAYERS = (\[.*?\]);", text, re.S).group(1))
    blob = base64.b64decode(re.search(r"export const WEIGHTS =\s*'([^']+)'", text).group(1))
    data = np.frombuffer(blob, dtype=np.int8)
    at = 0
    for layer in layers:
        outs, ins = layer["shape"]
        layer["w"] = (data[at:at + outs * ins].astype(np.float32) * layer["scale"]).reshape(outs, ins)
        at += outs * ins
    return layers


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--digits", required=True)
    ap.add_argument("--weights", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--count", type=int, default=CLASSES)
    args = ap.parse_args()

    net = Net()
    for layer, spec in zip([net.c1, net.c2, net.c3, net.f1, net.f2], read_weights(args.weights)):
        layer.w = spec["w"].copy()
        layer.b = np.asarray(spec["bias"], dtype=np.float32)

    x, y = load_digits(args.digits)
    _, _, xte, yte = split(x, y)
    picks = [int(np.where(yte == d)[0][0]) for d in range(min(args.count, CLASSES))]
    xs = xte[picks]
    out = net.forward(xs, train=False)

    cases = [
        {
            "label": int(yte[p]),
            "pixels": [round(float(v), 3) for v in xs[i].reshape(-1)],
            "logits": [round(float(v), 5) for v in out[i]],
        }
        for i, p in enumerate(picks)
    ]
    pathlib.Path(args.out).write_text(
        "// GENERATED by tools/train-digits/export_fixtures.py — do not edit by hand.\n"
        "//\n"
        "// Inputs, and the logits numpy produced for them using the *quantised* weights that\n"
        "// ship in ink/weights.js. ink/model.js re-implements this forward pass in JavaScript;\n"
        "// these pairs are how the two are held to the same answer, to well under a thousandth.\n\n"
        f"export const CASES = {json.dumps(cases)};\n"
    )
    print(f"wrote {args.out} — {len(cases)} cases")


if __name__ == "__main__":
    main()
