"""Emit a small set of held-out MNIST digits for the in-browser accuracy page.

Separate from train.py because this is data, not training: it needs no model and no
randomness beyond a fixed seed, so the file it writes is stable between runs.

    python3 export_samples.py --digits path/to/digits --out ../../games/pet-zoo/tests/ink-samples.js

These are bitmaps, not strokes, so they measure the classifier and not the whole pipeline —
which is exactly what they are for. The stroke half is measured by a corpus captured on the
accuracy page itself, from a real hand.
"""

import argparse
import base64
import json
import pathlib

import numpy as np

SIZE = 28
CLASSES = 10
PER_CLASS = 5  # the same held-out slice train.py reserves, sampled evenly


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--digits", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--per-class", type=int, default=PER_CLASS)
    args = ap.parse_args()

    images, labels = [], []
    for digit in range(CLASSES):
        raw = json.loads((pathlib.Path(args.digits) / f"{digit}.json").read_text())["data"]
        flat = np.asarray(raw, dtype=np.float32)
        samples = flat[: (len(flat) // (SIZE * SIZE)) * SIZE * SIZE].reshape(-1, SIZE * SIZE)
        # train.py holds out the first 100 of each digit; take from inside that slice so
        # nothing here was ever trained on.
        step = max(1, 100 // args.per_class)
        for i in range(0, args.per_class * step, step):
            images.append(np.clip(np.rint(samples[i] * 255), 0, 255).astype(np.uint8))
            labels.append(digit)

    packed = base64.b64encode(np.concatenate(images).tobytes()).decode()
    pathlib.Path(args.out).write_text(
        "// GENERATED by tools/train-digits/export_samples.py — do not edit by hand.\n"
        "//\n"
        f"// {len(labels)} held-out MNIST digits, 28x28, one byte per pixel, base64'd.\n"
        "// The accuracy page uses these to report how the JavaScript classifier does on real\n"
        "// digits. They are bitmaps, so they measure the model and not the stroke pipeline.\n\n"
        f"export const LABELS = {json.dumps(labels)};\n\n"
        f"export const PIXELS =\n  '{packed}';\n"
    )
    print(f"wrote {args.out} — {len(labels)} samples, {len(packed)} base64 chars")


if __name__ == "__main__":
    main()
